### PR TITLE
Update systemd unit and make it generic

### PR DESCRIPTION
**Pull request by MichaIng**
In systemd it is not necessary to fork a process into background which implies the need to use Type=forking and at best create a PID file to allow systemd tracking its state. Instead one can run any process in foreground and use default Type=simple which implies STDOUT to systemd journal.

Since this systemd unit does not use any fancy new options, it can be assumed to work on any distribution, as long as the python3 executable location is the same.

The --datadir cmd option, as used here, is obsolete since userdata/ inside the git/install root is the default, but we'll leave it present to make aware of it, since often one wants to store userdata on a different location.

### CODE REVIEW

**Comment by gmiranda** [comment]
Thanks, will have a look at it

**Review by gmiranda — COMMENTED** [review]
Here's a suggestion, I think it's better since you only have to fill the application path once, and it's a bit easier when using virtual environments.

**Comment by MichaIng** [comment]
Since user + group need to be altered as well, I personally would leave it as simple template without much magic to most importantly tell users that there is no special signal/process handling required. Since `--datadir` does not have any effect when anyway using `<HTPC>/userdata`, it is probably best to leave it as `/path/to/HTPCManager_data` to make it more clear that it can (and probably should) be placed at a different location instead of "binding" it to the git/install path even more with the environment variable?

Also I'm no big fan of shell wrappers around the actual process. This means there is an additional bash process running all the time and systemd is actually monitoring the bash process, not the Python process. In journal, logs will be prefixed with `bash` (this could be changed with `SyslogItentifier=HTPC Manager Daemon`) and all signals are send/received through bash relying on proper forwarding, and, even that bash of course is very robust, in theory it can fail while executing Htpc.py alone could have succeeded. At least I would use `sh` then, which defaults to the much more lightweight `dash` on Debian and Ubuntu and is assured to be present on any distro, while `bash` is no necessarily.
`exec` could probably solve it as it replaced the the parent shell with the process given as argument, but I never tested it within systemd units.

IMO, keep it as simple as possible without much magic, which assures it is portable. And users who manually install HTPC Manager with or without venv will know how to set the python and Htpc.py path.

**Comment by MichaIng** [comment]
I mark this as closed here, probably needs to more thoughts about having a template or an mostly OOTB functional default. There is more important things 😄.

**Pull request closed without merging**
